In [16]:
import pandas as pd
movies=pd.read_csv('tmdb_5000_movies.csv')
movies=movies[['id','title','overview','genres']]
movies.dropna(inplace=True)
movies.head()

       id  ...                                             genres
0   19995  ...  [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1     285  ...  [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2  206647  ...  [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3   49026  ...  [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4   49529  ...  [{"id": 28, "name": "Action"}, {"id": 12, "nam...

[5 rows x 4 columns]

In [21]:
import ast
def convert(obj):
  L=[]
  for i in ast.literal_eval(obj):
    L.append(i['name'])
  return L
movies['genres']=movies['genres'].apply(convert)
movies.head()

       id  ...                                         genres
0   19995  ...  [Action, Adventure, Fantasy, Science Fiction]
1     285  ...                   [Adventure, Fantasy, Action]
2  206647  ...                     [Action, Adventure, Crime]
3   49026  ...               [Action, Crime, Drama, Thriller]
4   49529  ...           [Action, Adventure, Science Fiction]

[5 rows x 4 columns]

In [27]:
movies['overview']=movies['overview'].apply(lambda x: x.split() if isinstance(x, str) else x)
movies['tags']=movies['genres']+movies['overview']
movies['tags']=movies['tags'].apply(lambda x:' '.join(x))
movies[['title','tags']].head()

                                      title                                               tags
0                                    Avatar  Action Adventure Fantasy Science Fiction In th...
1  Pirates of the Caribbean: At World's End  Adventure Fantasy Action Captain Barbossa, lon...
2                                   Spectre  Action Adventure Crime A cryptic message from ...
3                     The Dark Knight Rises  Action Crime Drama Thriller Following the deat...
4                               John Carter  Action Adventure Science Fiction John Carter i...

In [28]:
from sklearn.feature_extraction.text import CountVectorizer
#looks at top 5000 most common words and ignore stop words(like the is and etc)
cv=CountVectorizer(max_features=5000,stop_words='english')
vectors=cv.fit_transform(movies['tags']).toarray()
print(vectors.shape)

(643, 5000)

In [29]:
from sklearn.metrics.pairwise import cosine_similarity
#calulates similarity b/w every movie and every other movie
similarity=cosine_similarity(vectors)
print(similarity[0])

[1.         0.1860521  0.0860663  0.05976143 0.14704292 0.1490712
 0.02911113 0.23596995 0.09325048 0.1118034  0.20080483 0.10476454
 0.16269784 0.06523281 0.21516574 0.06523281 0.16064387 0.13187609
 0.0904534  0.09583148 0.07644708 0.08304548 0.10540926 0.14301939
 0.08944272 0.         0.2076137  0.18786729 0.18257419 0.09302605
 0.11338934 0.2795085  0.06388766 0.21081851 0.         0.21693046
 0.20701967 0.09128709 0.08385255 0.15118579 0.0766965  0.13187609
 0.         0.153393   0.07905694 0.14940358 0.23836565 0.15214515
 0.06030227 0.         0.12247449 0.1        0.17213259 0.06819943
 0.06454972 0.07547319 0.2        0.         0.06454972 0.10397505
 0.         0.25       0.13483997 0.06900656 0.1118034  0.03333333
 0.03535534 0.14509525 0.2795085  0.0451754  0.153393   0.11028219
 0.2236068  0.06454972 0.186339   0.07559289 0.15811388 0.
 0.09325048 0.14142136 0.05163978 0.06776309 0.14301939 0.20916501
 0.13975425 0.09759001 0.07352146 0.16903085 0.09759001 0.04016097
 0.1        0.20412415 0.07559289 0.10606602 0.20519567 0.13693064
 0.15811388 0.13968606 0.15       0.03834825 0.05976143 0.16609096
 0.14680505 0.12909944 0.10259784 0.10846523 0.07559289 0.13046561
 0.14322297 0.11547005 0.         0.16329932 0.0860663  0.08451543
 0.0766965  0.07559289 0.10741723 0.10540926 0.02515773 0.04303315
 0.         0.12247449 0.21081851 0.20519567 0.06666667 0.08489527
 0.11504475 0.19414507 0.         0.10112998 0.04082483 0.13801311
 0.03131121 0.05270463 0.1677051  0.         0.03627381 0.02294157
 0.15       0.15569979 0.06666667 0.06454972 0.07784989 0.09302605
 0.10259784 0.02961744 0.         0.08164966 0.15       0.20701967
 0.19878664 0.25819889 0.10259784 0.08588975 0.04662524 0.
 0.03580574 0.1        0.16854997 0.11547005 0.08195375 0.07905694
 0.0559017  0.11858541 0.09890707 0.15       0.18257419 0.09128709
 0.1767767  0.13187609 0.10350983 0.03834825 0.11547005 0.
 0.21128856 0.06523281 0.05773503 0.         0.03580574 0.05
 0.0372678  0.04082483 0.13801311 0.12171612 0.12524486 0.13987572
 0.06324555 0.15118579 0.03100868 0.06454972 0.05234239 0.08304548
 0.         0.09817614 0.         0.08944272 0.15       0.07071068
 0.09759001 0.186339   0.20225996 0.         0.04225771 0.15118579
 0.03627381 0.10540926 0.11009638 0.17213259 0.17320508 0.06201737
 0.0745356  0.02862992 0.13801311 0.10882144 0.03535534 0.12677314
 0.09759001 0.05923489 0.07071068 0.09759001 0.13987572 0.03892495
 0.10767638 0.11504475 0.075      0.11338934 0.         0.09534626
 0.17902872 0.09877296 0.13176157 0.         0.25       0.21081851
 0.10350983 0.08032193 0.08944272 0.09534626 0.14680505 0.08733338
 0.07905694 0.11858541 0.16609096 0.10882144 0.05       0.09534626
 0.03450328 0.         0.06984303 0.1677051  0.         0.
 0.03042903 0.0559017  0.07559289 0.         0.1677051  0.12677314
 0.02318694 0.09759001 0.19518001 0.04767313 0.11504475 0.15811388
 0.         0.048795   0.14301939 0.1118034  0.04225771 0.
 0.15811388 0.153393   0.         0.03370999 0.03984095 0.18650096
 0.1118034  0.08964215 0.153393   0.10741723 0.         0.0766965
 0.04662524 0.         0.         0.02731792 0.03492151 0.
 0.         0.05234239 0.1        0.07071068 0.15389675 0.0438529
 0.0860663  0.04303315 0.06900656 0.03627381 0.         0.05872202
 0.14509525 0.12060454 0.06900656 0.03892495 0.04767313 0.14142136
 0.12677314 0.08268982 0.05270463 0.08944272 0.05423261 0.186339
 0.1490712  0.05423261 0.         0.11028219 0.         0.
 0.         0.14638501 0.048795   0.         0.2795085  0.
 0.03492151 0.09128709 0.04472136 0.04767313 0.         0.12909944
 0.13416408 0.06085806 0.1204829  0.09534626 0.15811388 0.12456822
 0.10540926 0.03492151 0.         0.09325048 0.0766965  0.08451543
 0.13459548 0.03194383 0.04225771 0.03015113 0.         0.
 0.04303315 0.14638501 0.07784989 0.         0.0438529  0.02936101
 0.         0.06454972 0.1        0.         0.14301939 0.04564355
 0.         0.04303315 0.14638501 0.1        0.03162278 0.20412415
 0.11858541 0.         0.09325048 0.1490712  0.09128709 0.12524486
 0.07254763 0.19364917 0.05234239 0.05976143 0.09890707 0.
 0.         0.06993786 0.         0.12403473 0.         0.07559289
 0.04303315 0.         0.0372678  0.04303315 0.         0.09759001
 0.04472136 0.02795085 0.04564355 0.         0.04082483 0.
 0.04225771 0.         0.         0.03952847 0.16903085 0.
 0.07352146 0.16137431 0.048795   0.048795   0.03100868 0.03131121
 0.05270463 0.         0.14142136 0.06900656 0.15504342 0.13968606
 0.04472136 0.08588975 0.048795   0.06454972 0.         0.13968606
 0.21213203 0.         0.1860521  0.04082483 0.06388766 0.0860663
 0.10327956 0.04152274 0.0559017  0.         0.03779645 0.048795
 0.07352146 0.05       0.         0.05129892 0.         0.04152274
 0.         0.         0.         0.08304548 0.11858541 0.03627381
 0.         0.         0.04472136 0.03535534 0.         0.15
 0.06900656 0.03952847 0.04767313 0.04016097 0.12247449 0.05270463
 0.06523281 0.07905694 0.02672612 0.05270463 0.         0.16903085
 0.         0.         0.         0.         0.25       0.11744404
 0.04303315 0.06142951 0.03834825 0.07784989 0.1118034  0.22677868
 0.         0.10350983 0.14638501 0.         0.06523281 0.02599376
 0.10606602 0.         0.         0.25       0.05       0.08032193
 0.07745967 0.24806947 0.07745967 0.         0.20519567 0.06388766
 0.04082483 0.         0.         0.29880715 0.         0.
 0.09534626 0.         0.03834825 0.0745356  0.10606602 0.07559289
 0.         0.21693046 0.         0.19166297 0.17460757 0.03492151
 0.1315587  0.20519567 0.04082483 0.12456822 0.0372678  0.
 0.         0.         0.06593805 0.         0.         0.
 0.         0.06523281 0.         0.03952847 0.         0.
 0.04016097 0.16308202 0.048795   0.06666667 0.         0.05976143
 0.06741999 0.10606602 0.         0.10540926 0.         0.24397502
 0.06900656 0.09302605 0.08257228 0.09682458 0.08451543 0.08451543
 0.05129892 0.11952286 0.         0.11338934 0.         0.03409972
 0.         0.06201737 0.         0.02224971 0.04225771 0.07161149
 0.         0.         0.02454403 0.0559017  0.         0.03535534
 0.11952286 0.06388766 0.03370999 0.         0.18650096 0.0326164
 0.12909944 0.03227486 0.09890707 0.03450328 0.0326164  0.07559289
 0.04152274 0.18650096 0.02839809 0.05773503 0.03296902 0.2236068
 0.17213259 0.07905694 0.09128709 0.         0.06142951 0.15569979
 0.0372678  0.06593805 0.05129892 0.08164966 0.03409972 0.
 0.11952286 0.12649111 0.13046561 0.08451543 0.         0.02182179
 0.06388766 0.07032108 0.07071068 0.0766965  0.10259784 0.
 0.         0.11952286 0.         0.03676073 0.07798129 0.03535534
 0.06900656 0.05773503 0.05129892 0.05129892 0.         0.08944272
 0.18380366 0.         0.         0.05129892 0.02886751 0.
 0.11547005 0.         0.15811388 0.1677051  0.         0.03409972
 0.         0.03676073 0.10476454 0.03370999 0.24397502 0.04082483
 0.04016097 0.04767313 0.         0.         0.0766965  0.
 0.        ]

In [33]:
def recommend(movie):
  # Find the index of the movie
  movie_index = movies[movies['title'] == movie].index[0]

  # Get similarity scores for that movie index
  distances = similarity[movie_index]

  # Sort by highest similarity and get top 5 (excluding the movie itself)
  movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:6]

  for i in movies_list:
    print(movies.iloc[i[0]].title)
    # The AI only knows row numbers. Take the number [i[0]] and look up the actual title so a huamn can read it

recommend('Iron Man')

Iron Man 3
Avengers: Age of Ultron
Iron Man 2
Star Wars: Episode I - The Phantom Menace
Avatar